version = "1.0"

[main]
name.en = "Streams configuration"
name.fr = "Configuration de Streams"

    [main.php_fpm_config]
    name.en = "PHP-FPM configuration"
    name.fr = "Configuration de PHP-FPM"

        [main.php_fpm_config.fpm_footprint]
        ask.en = "Memory footprint"
        ask.fr = "Empreinte mémoire"
        type = "select"
        choices = ["low", "medium", "high", "specific"]
        default = "medium"
        help.en = "<strong>low</strong>: <= 20Mb per pool<br><strong>medium</strong>: Between 20Mb and 40Mb per pool<br><strong>high</strong>: 40Mb per pool<br><strong>specific</strong> : Use specific value"
        help.fr = "<strong>low</strong>: <= 20Mb par pool<br><strong>medium</strong>: Entre 20Mb et 40Mb par pool<br><strong>high</strong>: 40Mb par pool<br><strong>specific</strong> : Utiliser une valeur personnalisée"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific'"
        ask.en = "Memory footprint of the service?"
        ask.fr = "Empreinte mémoire du service?"
        type = "number"
        default = "0"
        help.en = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."
        help.fr = "Champ libre pour spécifier exactement l'empreinte mémoire en Mb si vous ne souhaitez pas utiliser l'une des trois valeurs précédentes."

        [main.php_fpm_config.fpm_usage]
        ask.en = "Expected usage"
        ask.fr = "Utilisation prévue"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "medium"
        help.en = "<strong>low</strong>: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br><strong>medium</strong>: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br><strong>high</strong>: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
        help.fr = "<strong>low</strong> : Utilisation personnelle, derrière le SSO. Pas d'empreinte RAM en cas de non-utilisation, mais l'impact sur le processeur peut être élevé si de nombreux utilisateurs utilisent le service.<br><strong>medium</strong> : Faible utilisation, peu d'utilisateurs et/ou service pas nécessairement accessible au public. Faible empreinte RAM, empreinte moyenne sur le processeur en cas d'utilisation.<br><strong>high</strong> : Utilisation soutenue, site web fréquemment visité. L'empreinte RAM est élevée, mais l'utilisation du processeur est moindre et le service répond rapidement."

    [main.phpmailer_config]
    name.en = "PHPMailer configuration"
    name.fr = "Configuration de PHPMailer"

        [main.phpmailer_config.phpmailer_activate]
        ask.en = "Activate PHPMailer"
        ask.fr = "Activer PHPMailer"
        type = "boolean"
        default = "0"
        help.en = "Enabling this option allows you to use 'PHPMailer' instead of built-in mail() function. This can be a solution if the emails generated and sent by your site do not always reach their intended recipients."
        help.fr = "Activer cette option vous permet d'utiliser 'PHPMailer' au lieu de la fonction mail() intégrée. Ceci peut être une solution si les courriels générés et envoyés par votre site ne parviennent pas toujours à leurs destinaires."

        [main.phpmailer_config.phpmailer_local_smtp_server]
        visible = "phpmailer_activate == '1'"
        ask.en = "Use your YunoHost server's SMTP"
        ask.fr = "Utiliser le SMTP de votre serveur YunoHost"
        type = "boolean"
        default = "1"
        help.en = "<strong>Yes</strong>: Recommended option. Your YunoHost server has a SMTP server, so the easiest thing to do is to use it.<br><strong>Non</strong>: You can choose to use an external SMTP server with secure authentication. In this case, you will need to provide a certain amount of additional information."
        help.fr = "<strong>Oui</strong> : Option recommandée. Votre serveur YunoHost dispose d'un serveur SMTP, le plus simple est de l'utiliser.<br><strong>Non</strong> : Vous pouvez choisir de passer par un serveur SMTP externe utilisant une authentification sécurisée. Vous devrez dans ce cas fournir un certain nombre d'informations supplémentaires."

        [main.phpmailer_config.phpmailer_custom_smtp_server]
        visible = "phpmailer_activate == '1' && phpmailer_local_smtp_server == '0'"
        ask.en = "SMTP server address"
        ask.fr = "Adresse du serveur SMTP"
        type = "string"
        example = "smtp.example.com"
        pattern.regexp = '^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}$'
        pattern.error = 'Enter a valid domain'
        help.en = "Address of the SMTP server you wish to use. Enter the domain or sub-domain alone, without \"https://\" or \"http://\"."
        help.fr = "Adresse du serveur SMTP que vous souhaitez utiliser. Entrez le domaine ou le sous-domaine seul, sans \"https://\" ou \"http://\"."

        [main.phpmailer_config.phpmailer_smtp_username]
        visible = "phpmailer_activate == '1' && phpmailer_local_smtp_server == '0'"
        ask.en = "Username"
        ask.fr = "Nom d'utilisateur"
        type = "string"
        help.en = "Username to be used for authentication on your SMTP server. Please check whether it must be entered in the form \"username\" or \"username@smtp.example.com\"."
        help.fr = "Nom d'utilisateur à utiliser pour l'authentification sur votre serveur SMTP. Attention, vérifiez bien s'il doit être saisi sous la forme \"username\" ou \"username@smtp.example.com\"."

        [main.phpmailer_config.phpmailer_smtp_password]
        visible = "phpmailer_activate == '1' && phpmailer_local_smtp_server == '0'"
        ask.en = "Password"
        ask.fr = "Mot de passe"
        type = "password"
        help.en = "Password to be used for authentication on your SMTP server."
        help.fr = "Mot de passe à utiliser pour l'authentification sur votre serveur SMTP."

        [main.phpmailer_config.phpmailer_smtp_encryption]
        visible = "phpmailer_activate == '1' && phpmailer_local_smtp_server == '0'"
        ask.en = "Encryption method"
        ask.fr = "Méthode de chiffrement"
        type = "select"
        choices = ["STARTTLS", "SSL"]
        help.en = "You need to check which encryption method is used by your SMTP provider. You should be able to find the necessary information in your provider's documentation on how to configure your email client (<a href=\"https://yunohost.org/en/email_configure_client\">example</a>)."
        help.fr = "Vous devez vérifier quelle méthode de chiffrement est utilisée par votre fournisseur SMTP. Vous devriez pouvoir trouver les informations nécessaires dans la documentation de votre fournisseur sur la manière de configurer votre client de messagerie (<a href=\"https://yunohost.org/fr/email_configure_client\">exemple</a>)."

        [main.phpmailer_config.phpmailer_smtp_self_signed]
        visible = "phpmailer_activate == '1' && phpmailer_local_smtp_server == '0'"
        ask.en = "Self-signed certificate"
        ask.fr = "Certificat auto-signé"
        type = "boolean"
        default = "0"
        help.en = "Enable this option if the SMTP server uses a self-signed certificate. <strong>If you don't understand the previous sentence, don't touch anything</strong>."
        help.fr = "Activer cette option si le serveur SMTP utilise un certificat auto-signé. <strong>Si vous ne comprenez pas la phrase précédente, ne touchez à rien</strong>."

        [main.phpmailer_config.phpmailer_sender_address]
        visible = "phpmailer_activate == '1'"
        ask.en = "Sender's email"
        ask.fr = "Courriel de l'expéditeur"
        type = "string"
        default = "Administrator@__DOMAIN__"
        pattern.regexp = '^[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:].]{2,12}$'
        pattern.error = 'Enter a valid email adress'
        help.en = "Sender's email address (\"From\" field) for emails generated by your website. This address must <strong>imperatively</strong> use a domain name managed by your YunoHost server. Any incorrect address will prevent PHPMailer's configuration from being validated."
        help.fr = "Adresse de courriel de l'expéditeur (champ \"De\") pour les courriels générés par votre site. Cette adresse doit <strong>impérativement</strong> utiliser un nom de domaine géré par votre serveur YunoHost. Toute adresse incorrecte empêchera la validation de la configuration de PHPMailer."

    [main.git_branch_mode]
    name.en = "Developer Mode"
    name.fr = "Mode Développeur"

        [main.git_branch_mode.git_branch_mode]
        ask.en = "Switch to 'dev' branch"
        ask.fr = "Basculer sur la branche 'dev'"
        type = "boolean"
        default = "0"
        help.en = "<strong>This option should only be used if you're either a professional software developer or a certified lunatic (or both).</strong><br><br>You can only return to the 'release' branch if it is ahead of the 'dev' branch.<br><br>If authorised, the switch to the 'release' branch will be immediately followed by a global update of the site - via the util/udall command.<br><br>You must be able to use the command line to solve any problems you may encounter after using this option.<br><br>If you haven't understood any of the above lines <strong>DON'T USE THIS OPTION!!!</strong>"
        help.fr = "<strong>Cette option ne devrait être utilisée que si vous êtes un développeur de logiciels professionnel ou une personne passablement déraisonnable (ou les deux à la fois)</strong><br><br>Vous ne pourrez revenir à la branche 'release' que si celle-ci est en avance sur la branche 'dev'.<br><br>Si elle est autorisée, la bascule vers la branche 'release' sera immédiatement suivie d'une mise à jour globale du site - via la commande util/udall.<br><br>Vous devez impérativement être capable d'utiliser la ligne de commande pour résoudre tout problème que vous pourriez rencontrer après avoir utilisé cette option.<br><br>Si vous n'avez rien compris aux lignes ci-dessus <strong>N'UTILISEZ PAS CETTE OPTION!!!</strong>"
